### ISSUE TITLE
Words should not have accents

### ISSUE THREAD

**Issue by wongvincent** [wongvincent/TypeRacer#3]
Words shouldn't have accents e.g. é è

**Comment by ghost** [comment]
Approach 1: Wordnik API might have property to only return words with A-Z
Con: I don't think it exists

Approach 2: Send request for number of words needed to put on canvas, manually sift through each one, if word contains accent discard it and send a request to wordnik's singular random word and place that at the end
Con: Expensive

**Approach 3**: Send request for an excess number of words, if words have accents drop them. If number of words dips below the number of words required (check each time array is spliced) send request to wordnik /random
